import 'package:bitfinite/gowallet/l10n/go_localizations.dart';
/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_svg/svg.dart';

import '../app_config.dart';
import '../pages_desktop_specific/password/create_password_view.dart';
import '../themes/stack_colors.dart';
import '../themes/theme_providers.dart';
import '../utilities/prefs.dart';
import '../utilities/text_styles.dart';
import '../utilities/util.dart';
import '../widgets/app_icon.dart';
import '../widgets/background.dart';
import '../widgets/desktop/secondary_button.dart';
import 'stack_privacy_calls.dart';
import 'pinpad_views/create_pin_view.dart';
import '../gowallet/go_ui.dart';

class IntroView extends ConsumerStatefulWidget {
  const IntroView({super.key});

  static const String routeName = "/introView";

  @override
  ConsumerState<IntroView> createState() => _IntroViewState();
}

class _IntroViewState extends ConsumerState<IntroView> {
  late final bool isDesktop;

  @override
  void initState() {
    isDesktop = Util.isDesktop;
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    debugPrint("BUILD: $runtimeType ");
    final stack = ref.watch(
      themeProvider.select((value) => value.assets.stack),
    );
    return Background(
      child: Scaffold(
        backgroundColor: Theme.of(context).extension<StackColors>()!.background,
        body: SafeArea(
          child: Center(
            child: !isDesktop
                ? SingleChildScrollView(
                    padding: const EdgeInsets.all(28),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 36),
                        const GoMark(size: 76),
                        const SizedBox(height: 24),
                        Text(
                          goTr(context, "GOwallet"),
                          style: TextStyle(
                            fontSize: 38,
                            fontWeight: FontWeight.w800,
                          ),
                        ),
                        const SizedBox(height: 8),
                        Text(
                          goTr(context, "让每一份算力，\n都有自己的归处。"),
                          style: TextStyle(
                            fontSize: 28,
                            height: 1.4,
                            fontWeight: FontWeight.w700,
                          ),
                        ),
                        const SizedBox(height: 18),
                        Text(
                          goTr(
                            context,
                            "为小型 PoW 网络而生的自托管钱包。\n支持 SCASH、SHIC、PEP 和自定义币种。",
                          ),
                          style: TextStyle(fontSize: 15, height: 1.6),
                        ),
                        const SizedBox(height: 32),
                        GoNotice(
                          title: goTr(context, "密钥留在你的设备"),
                          detail: goTr(context, "离线备份助记词。我们无法重置它，也无法替你找回资产。"),
                          icon: Icons.key_rounded,
                        ),
                        const SizedBox(height: 12),
                        GoNotice(
                          title: goTr(context, "明白连接，也明白风险"),
                          detail: goTr(
                            context,
                            "默认连接使用 TLS 加密。服务器仍能看到地址查询，请选择可信节点。",
                          ),
                          icon: Icons.hub_outlined,
                        ),
                        const SizedBox(height: 28),
                        SizedBox(
                          width: double.infinity,
                          child: FilledButton(
                            style: FilledButton.styleFrom(
                              backgroundColor: GoPalette.teal,
                              foregroundColor: Colors.white,
                              minimumSize: const Size.fromHeight(54),
                            ),
                            onPressed: () {
                              Prefs.instance.externalCalls = false;
                              Prefs.instance.autoLockInfo = (
                                enabled: true,
                                minutes: 1,
                              );
                              Navigator.of(
                                context,
                              ).pushNamed(CreatePinView.routeName);
                            },
                            child: Text(goTr(context, "设置安全 PIN · 开始使用")),
                          ),
                        ),
                        const SizedBox(height: 16),
                        Text(
                          goTr(context, "自托管需要你妥善保管设备和备份。请先用小额资产验证收发流程。"),
                          style: TextStyle(fontSize: 12, height: 1.6),
                        ),
                      ],
                    ),
                  )
                : SizedBox(
                    width: 350,
                    height: 540,
                    child: Column(
                      children: [
                        const Spacer(flex: 2),
                        const SizedBox(
                          width: 130,
                          height: 130,
                          child: AppIcon(),
                        ),
                        const Spacer(flex: 42),
                        AppNameText(isDesktop: isDesktop),
                        const Spacer(flex: 24),
                        IntroAboutText(isDesktop: isDesktop),
                        const Spacer(flex: 42),
                        GetStartedButton(isDesktop: isDesktop),
                        if (isDesktop) const SizedBox(height: 20),
                        if (isDesktop)
                          SecondaryButton(
                            label: goTr(context, "Restore from {0} backup", [
                              AppConfig.prefix,
                            ]),
                            onPressed: () {
                              Navigator.of(context).pushNamed(
                                CreatePasswordView.routeName,
                                arguments: true,
                              );
                            },
                          ),
                        const Spacer(flex: 65),
                        PrivacyAndTOSText(isDesktop: isDesktop),
                      ],
                    ),
                  ),
          ),
        ),
      ),
    );
  }
}

class AppNameText extends StatelessWidget {
  const AppNameText({super.key, required this.isDesktop});

  final bool isDesktop;

  @override
  Widget build(BuildContext context) {
    return Text(
      AppConfig.appName,
      textAlign: TextAlign.center,
      style: !isDesktop
          ? STextStyles.pageTitleH1(context)
          : STextStyles.pageTitleH1(context).copyWith(fontSize: 40),
    );
  }
}

class IntroAboutText extends StatelessWidget {
  const IntroAboutText({super.key, required this.isDesktop});

  final bool isDesktop;

  @override
  Widget build(BuildContext context) {
    return Text(
      AppConfig.shortDescriptionText,
      textAlign: TextAlign.center,
      style: !isDesktop
          ? STextStyles.subtitle(context)
          : STextStyles.subtitle(context).copyWith(fontSize: 24),
    );
  }
}

class PrivacyAndTOSText extends StatelessWidget {
  const PrivacyAndTOSText({super.key, required this.isDesktop});

  final bool isDesktop;

  @override
  Widget build(BuildContext context) {
    final fontSize = isDesktop ? 18.0 : 12.0;
    return Text(
      goTr(
        context,
        "Recovery phrases and keys stay on this device. Your selected Electrum server sees address queries and transaction data. TCP connections are unencrypted; choose TLS when your server supports it.",
      ),
      textAlign: TextAlign.center,
      style: STextStyles.label(context).copyWith(fontSize: fontSize),
    );
  }
}

class GetStartedButton extends StatelessWidget {
  const GetStartedButton({super.key, required this.isDesktop});

  final bool isDesktop;

  @override
  Widget build(BuildContext context) {
    return !isDesktop
        ? TextButton(
            style: Theme.of(
              context,
            ).extension<StackColors>()!.getPrimaryEnabledButtonStyle(context),
            onPressed: () {
              Prefs.instance.externalCalls = false;
              Navigator.of(
                context,
              ).pushNamed(StackPrivacyCalls.routeName, arguments: false);
            },
            child: Text(
              goTr(context, "Get started"),
              style: STextStyles.button(context),
            ),
          )
        : SizedBox(
            width: double.infinity,
            height: 70,
            child: TextButton(
              style: Theme.of(
                context,
              ).extension<StackColors>()!.getPrimaryEnabledButtonStyle(context),
              onPressed: () {
                Navigator.of(
                  context,
                ).pushNamed(StackPrivacyCalls.routeName, arguments: false);
              },
              child: Text(
                goTr(context, "Create new {0}", [AppConfig.prefix]),
                style: STextStyles.button(context).copyWith(fontSize: 20),
              ),
            ),
          );
  }
}
