import 'package:bitfinite/gowallet/l10n/go_localizations.dart';
/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:async';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_svg/svg.dart';

import '../../../providers/providers.dart';
import '../../../themes/coin_icon_provider.dart';
import '../../../themes/stack_colors.dart';
import '../../../utilities/amount/amount.dart';
import '../../../utilities/constants.dart';
import '../../../utilities/show_loading.dart';
import '../../../utilities/show_node_tor_settings_mismatch.dart';
import '../../../utilities/text_styles.dart';
import '../../../utilities/util.dart';
import '../../../wallets/crypto_currency/coins/solana.dart';
import '../../../wallets/crypto_currency/crypto_currency.dart';
import '../../../wallets/isar/providers/wallet_info_provider.dart';
import '../../../wallets/isar/providers/all_wallets_info_provider.dart';
import '../../../wallets/wallet/intermediate/external_wallet.dart';
import '../../../widgets/dialogs/tor_warning_dialog.dart';
import '../../../widgets/rounded_white_container.dart';
import '../../wallet_view/wallet_view.dart';
import '../wallets_overview.dart';

class WalletListItem extends ConsumerWidget {
  const WalletListItem({
    super.key,
    required this.coin,
    required this.walletCount,
  });

  final CryptoCurrency coin;
  final int walletCount;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // debugPrint("BUILD: $runtimeType");
    final walletCountString = walletCount == 1
        ? goTr(context, '1 个钱包')
        : goTr(context, '{0} 个钱包', [walletCount]);
    final currency = ref.watch(
      prefsChangeNotifierProvider.select((value) => value.currency),
    );

    return RoundedWhiteContainer(
      padding: const EdgeInsets.all(0),
      child: MaterialButton(
        // splashColor: Theme.of(context).extension<StackColors>()!.highlight,
        key: Key("walletListItemButtonKey_${coin.identifier}"),
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 17),
        materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(
            Constants.size.circularBorderRadius,
          ),
        ),
        onPressed: () => openWalletGroup(context, ref, coin, walletCount),
        child: Row(
          children: [
            SvgPicture.file(
              File(ref.watch(coinIconProvider(coin))),
              width: 40,
              height: 40,
            ),
            const SizedBox(width: 12),
            Expanded(
              child: Consumer(
                builder: (_, ref, __) {
                  Color percentChangedColor = Theme.of(
                    context,
                  ).extension<StackColors>()!.textDark;
                  String? priceString;
                  double? percentChange;
                  if (ref.watch(
                    prefsChangeNotifierProvider.select((s) => s.externalCalls),
                  )) {
                    final price = ref.watch(
                      priceAnd24hChangeNotifierProvider.select(
                        (value) => value.getPrice(coin),
                      ),
                    );

                    if (price != null) {
                      // 8, not 2: quantising to two decimals here destroyed any
                      // price below a cent. PEP showed $0.00 beside a +23% change.
                      priceString = price.value
                          .toAmount(fractionDigits: 8)
                          .fiatString(
                            locale: ref.watch(
                              localeServiceChangeNotifierProvider.select(
                                (value) => value.locale,
                              ),
                            ),
                          );
                      percentChange = price.change24h;

                      if (percentChange > 0) {
                        percentChangedColor = Theme.of(
                          context,
                        ).extension<StackColors>()!.accentColorGreen;
                      } else if (percentChange < 0) {
                        percentChangedColor = Theme.of(
                          context,
                        ).extension<StackColors>()!.accentColorRed;
                      }
                    }
                  }

                  return Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      Row(
                        children: [
                          Text(
                            coin.prettyName,
                            style: STextStyles.titleBold12(
                              context,
                            ).copyWith(fontSize: 15),
                          ),
                          const Spacer(),
                          if (priceString != null)
                            Text(
                              "$priceString $currency/${coin.ticker}",
                              style: STextStyles.itemSubtitle(context),
                            ),
                        ],
                      ),
                      const SizedBox(height: 1),
                      Row(
                        children: [
                          Text(
                            walletCountString,
                            style: STextStyles.itemSubtitle(context),
                          ),
                          const Spacer(),
                          if (percentChange != null)
                            Text(
                              "${percentChange.toStringAsFixed(2)}%",
                              style: STextStyles.itemSubtitle(
                                context,
                              ).copyWith(color: percentChangedColor),
                            ),
                        ],
                      ),
                    ],
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}

Future<void> openWalletGroup(
  BuildContext context,
  WidgetRef ref,
  CryptoCurrency coin,
  int walletCount,
) async {
  // Check if Tor is enabled...
  if (ref.read(prefsChangeNotifierProvider).useTor) {
    // ... and if the coin supports Tor.
    if (!coin.torSupport) {
      // If not, show a Tor warning dialog.
      final shouldContinue =
          await showDialog<bool>(
            context: context,
            builder: (_) => TorWarningDialog(coin: coin),
          ) ??
          false;
      if (!shouldContinue) {
        return;
      }
    }
  }

  if (!context.mounted) return;
  final visibleIds = ref.read(pAllWalletsInfo).map((w) => w.walletId).toSet();
  final matchingWallets = ref
      .read(pWallets)
      .wallets
      .where((w) => w.info.coin == coin && visibleIds.contains(w.walletId))
      .toList();
  if (matchingWallets.isEmpty) return;
  walletCount = matchingWallets.length;

  // Check if we should show the wallets overview or open wallet directly.
  bool shouldShowWalletsOverview = walletCount > 1 || coin is Ethereum;

  // For Solana and other token-supporting coins, check if any wallet has tokens.
  if (!shouldShowWalletsOverview && coin.hasTokenSupport) {
    final wallet = matchingWallets.first;

    final tokenAddresses = ref.read(pWalletTokenAddresses(wallet.walletId));
    if (tokenAddresses.isNotEmpty) {
      shouldShowWalletsOverview = true;
    }
  }

  if (walletCount == 1 && !shouldShowWalletsOverview) {
    final wallet = matchingWallets.first;

    final canContinue = await checkShowNodeTorSettingsMismatch(
      context: context,
      currency: coin,
      prefs: ref.read(prefsChangeNotifierProvider),
      nodeService: ref.read(nodeServiceChangeNotifierProvider),
      allowCancel: true,
      rootNavigator: Util.isDesktop,
    );

    if (!canContinue || !context.mounted) {
      return;
    }

    final Future<void> loadFuture;
    if (wallet is ExternalWallet) {
      loadFuture = wallet.init().then((value) async => await (wallet).open());
    } else {
      loadFuture = wallet.init();
    }
    await showLoading(
      whileFuture: loadFuture,
      context: context,
      message: goTr(context, "Opening {0}", [wallet.info.name]),
      rootNavigator: Util.isDesktop,
    );
    if (context.mounted) {
      unawaited(
        Navigator.of(
          context,
        ).pushNamed(WalletView.routeName, arguments: wallet.walletId),
      );
    }
  } else {
    unawaited(
      Navigator.of(
        context,
      ).pushNamed(WalletsOverview.routeName, arguments: coin),
    );
  }
}
