import 'package:bitfinite/gowallet/l10n/go_localizations.dart';
/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/material.dart';

import '../../../../../app_config.dart';
import '../../../../../themes/stack_colors.dart';
import '../../../../../utilities/text_styles.dart';
import '../../../../../utilities/util.dart';
import '../../../../../widgets/desktop/desktop_dialog.dart';
import '../../../../../widgets/desktop/primary_button.dart';
import '../../../../../widgets/desktop/secondary_button.dart';
import '../../../../../widgets/rounded_container.dart';
import '../../../../../widgets/stack_dialog.dart';

class CancelStackRestoreDialog extends StatelessWidget {
  const CancelStackRestoreDialog({super.key});

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () async {
        return false;
      },
      child: !Util.isDesktop
          ? StackDialog(
              title: goTr(context, "Cancel restore process"),
              message: goTr(
                context,
                "Cancelling will revert any changes that may have been applied",
              ),
              leftButton: TextButton(
                style: Theme.of(context)
                    .extension<StackColors>()!
                    .getSecondaryEnabledButtonStyle(context),
                child: Text(
                  goTr(context, "Back"),
                  style: STextStyles.itemSubtitle12(context),
                ),
                onPressed: () {
                  Navigator.of(context).pop(false);
                },
              ),
              rightButton: TextButton(
                style: Theme.of(context)
                    .extension<StackColors>()!
                    .getPrimaryEnabledButtonStyle(context),
                child: Text(
                  goTr(context, "Yes, cancel"),
                  style: STextStyles.itemSubtitle12(context).copyWith(
                    color: Theme.of(
                      context,
                    ).extension<StackColors>()!.buttonTextPrimary,
                  ),
                ),
                onPressed: () {
                  Navigator.of(context).pop(true);
                },
              ),
            )
          : DesktopDialog(
              maxHeight: 250,
              maxWidth: 600,
              child: Padding(
                padding: const EdgeInsets.only(
                  top: 20,
                  left: 32,
                  right: 32,
                  bottom: 20,
                ),
                child: Column(
                  children: [
                    Text(
                      goTr(context, "Cancel Restore Process"),
                      style: STextStyles.desktopH3(context),
                    ),
                    const SizedBox(height: 24),
                    SizedBox(
                      width: 500,
                      child: RoundedContainer(
                        color: Theme.of(
                          context,
                        ).extension<StackColors>()!.snackBarBackError,
                        child: Text(
                          goTr(
                            context,
                            "If you cancel, the restore will not complete, and the wallets will not appear in your {0}.",
                            [AppConfig.prefix],
                          ),
                          style: STextStyles.desktopTextMedium(context),
                        ),
                      ),
                    ),
                    const Spacer(),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        SecondaryButton(
                          width: 248,
                          buttonHeight: ButtonHeight.l,
                          enabled: true,
                          label: goTr(context, "Keep restoring"),
                          onPressed: () {
                            Navigator.of(context).pop(false);
                          },
                        ),
                        const SizedBox(width: 20),
                        PrimaryButton(
                          width: 248,
                          buttonHeight: ButtonHeight.l,
                          enabled: true,
                          label: goTr(context, "Cancel anyway"),
                          onPressed: () {
                            Navigator.of(context).pop(true);
                          },
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),
    );
  }
}
