/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/material.dart';

import '../../themes/stack_colors.dart';
import '../../utilities/assets.dart';

class RotatingArrowsController {
  VoidCallback? forward;
  VoidCallback? repeat;
  VoidCallback? stop;

  bool hasLoadedAnimation = false;
}

class RotatingArrows extends StatefulWidget {
  const RotatingArrows({
    super.key,
    required this.height,
    required this.width,
    this.controller,
    this.color,
    this.spinByDefault = true,
  });

  final double height;
  final double width;
  final RotatingArrowsController? controller;
  final Color? color;
  final bool spinByDefault;

  @override
  State<RotatingArrows> createState() => _RotatingArrowsState();
}

class _RotatingArrowsState extends State<RotatingArrows>
    with SingleTickerProviderStateMixin {
  late final AnimationController animationController;

  @override
  void initState() {
    animationController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 1100),
    );

    widget.controller?.forward = animationController.forward;
    widget.controller?.repeat = animationController.repeat;
    widget.controller?.stop = animationController.stop;

    widget.controller?.hasLoadedAnimation = true;
    if (widget.spinByDefault) animationController.repeat();
    super.initState();
  }

  @override
  void didUpdateWidget(RotatingArrows oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.spinByDefault != widget.spinByDefault) {
      if (widget.spinByDefault) {
        animationController.repeat();
      } else {
        animationController.stop();
      }
    }
  }

  @override
  void dispose() {
    animationController.dispose();
    widget.controller?.forward = null;
    widget.controller?.repeat = null;
    widget.controller?.stop = null;
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final icon = Icon(
      Icons.sync_rounded,
      size: widget.width,
      color: widget.color ?? Theme.of(context).colorScheme.primary,
    );
    return SizedBox(
      width: widget.width,
      height: widget.height,
      child: MediaQuery.disableAnimationsOf(context)
          ? icon
          : RotationTransition(turns: animationController, child: icon),
    );
  }
}
