import 'package:bitfinite/gowallet/l10n/go_localizations.dart';
import '../../gowallet/go_session_gate.dart';
/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:async';
import 'dart:io';

import 'package:flutter/cupertino.dart' show CupertinoIcons;
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_svg/svg.dart';

import '../../utilities/ios_icon.dart';

import '../../app_config.dart';
import '../../gowallet/go_dashboard.dart';
import '../../gowallet/go_control_pages.dart';
import '../../gowallet/go_ui.dart';
import '../wallets_view/sub_widgets/wallet_list_item.dart';
import '../../providers/global/notifications_provider.dart';
import '../../providers/global/prefs_provider.dart';
import '../../providers/ui/home_view_index_provider.dart';
import '../../providers/ui/unread_notifications_provider.dart';
import '../../route_generator.dart';
import '../../services/event_bus/events/global/tor_connection_status_changed_event.dart';
import '../../themes/stack_colors.dart';
import '../../themes/theme_providers.dart';
import '../../utilities/assets.dart';
import '../../utilities/constants.dart';
import '../../utilities/idle_monitor.dart';
import '../stack_privacy_calls.dart';
import '../../utilities/prefs.dart';
import '../../utilities/text_styles.dart';
import '../../utilities/util.dart';
import '../../widgets/animated_widgets/rotate_icon.dart';
import '../../widgets/app_icon.dart';
import '../../widgets/background.dart';
import '../../widgets/custom_buttons/app_bar_icon_button.dart';
import '../../widgets/small_tor_icon.dart';
import '../../widgets/stack_dialog.dart';
import '../buy_view/buy_view.dart';
import '../exchange_view/exchange_view.dart';
import '../notification_views/notifications_view.dart';
import '../pinpad_views/lock_screen_view.dart';
import '../settings_views/global_settings_view/global_settings_view.dart';
import '../settings_views/global_settings_view/hidden_settings.dart';
import '../wallets_view/wallets_view.dart';
import 'sub_widgets/home_view_button_bar.dart';

class HomeView extends ConsumerStatefulWidget {
  const HomeView({super.key});

  static const routeName = "/home";

  @override
  ConsumerState<HomeView> createState() => _HomeViewState();
}

class _HomeViewState extends ConsumerState<HomeView>
    with WidgetsBindingObserver {
  final GlobalKey<ScaffoldState> _key = GlobalKey<ScaffoldState>();

  // keep reference to be able to remove listener in dispose without requiring the riverpod ref
  late final Prefs _prefs;

  late final RotateIconController _rotateIconController;

  late final List<Widget> _children;

  DateTime? _cachedTime;

  bool _exitEnabled = false;

  late TorConnectionStatus _currentSyncStatus;

  IdleMonitor? _idleMonitor;

  bool _lockOnResume = false;

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.paused && !goSessionLocked.value)
      _lockOnResume = true;
    if (state == AppLifecycleState.resumed && _lockOnResume) {
      _lockOnResume = false;
      _onIdle();
    }
  }

  void _onIdle() {
    if (!mounted) return;
    goSessionLocked.value = true;
  }

  late AutoLockInfo _autoLockInfo;
  void _prefsTimeoutListener() {
    final prefs = ref.read(prefsChangeNotifierProvider);
    if (mounted && prefs.autoLockInfo != _autoLockInfo) {
      _autoLockInfo = prefs.autoLockInfo;
      if (_autoLockInfo.enabled) {
        _idleMonitor?.detach();
        _idleMonitor = IdleMonitor(
          timeout: Duration(minutes: _autoLockInfo.minutes),
          onIdle: _onIdle,
        );
        _idleMonitor!.attach();
      } else {
        _idleMonitor?.detach();
        _idleMonitor = null;
      }
    }
  }

  // final _buyDataLoadingService = BuyDataLoadingService();

  Future<bool> _onWillPop() async {
    if (_key.currentState?.isDrawerOpen == true) {
      _key.currentState?.closeDrawer();
      return false;
    }
    // go to home view when tapping back on the main exchange view
    if (ref.read(homeViewPageIndexStateProvider.state).state != 0) {
      ref.read(homeViewPageIndexStateProvider.state).state = 0;
      return false;
    }

    if (_exitEnabled) {
      return true;
    }

    final now = DateTime.now();
    const timeout = Duration(milliseconds: 1500);
    if (_cachedTime == null || now.difference(_cachedTime!) > timeout) {
      _cachedTime = now;
      await showDialog<dynamic>(
        context: context,
        barrierDismissible: false,
        builder: (_) => WillPopScope(
          onWillPop: () async {
            _exitEnabled = true;
            return true;
          },
          child: StackDialog(title: goTr(context, "Tap back again to exit")),
        ),
      ).timeout(
        timeout,
        onTimeout: () {
          _exitEnabled = false;
          Navigator.of(context).pop();
        },
      );
    }
    return _exitEnabled;
  }

  // void _loadSimplexData() {
  //   // unawaited future
  //   if (ref.read(prefsChangeNotifierProvider).externalCalls) {
  //     _buyDataLoadingService.loadAll(ref);
  //   } else {
  //     Logging.instance.log("User does not want to use external calls",
  //         level: LogLevel.Info);
  //   }
  // }

  Future<void> precacheSettingsIcons(BuildContext context) async {
    if (Util.isDesktop) return;

    final icons = [
      Assets.svg.addressBook,
      Assets.svg.downloadFolder,
      Assets.svg.lock,
      Assets.svg.dollarSign,
      Assets.svg.language,
      Assets.svg.node,
      Assets.svg.arrowRotate,
      Assets.svg.arrowUpRight,
      Assets.svg.sun,
      Assets.svg.circleAlert,
      Assets.svg.ellipsis,
      Assets.svg.solidSliders,
      Assets.svg.questionMessage,
    ];

    for (final asset in icons) {
      final loader = SvgAssetLoader(asset);
      await svg.cache.putIfAbsent(
        loader.cacheKey(context),
        () => loader.loadBytes(context),
      );
    }
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();

    precacheSettingsIcons(context);
  }

  @override
  void initState() {
    WidgetsBinding.instance.addObserver(this);
    _prefs = ref.read(prefsChangeNotifierProvider);
    _autoLockInfo = ref.read(prefsChangeNotifierProvider).autoLockInfo;
    if (_autoLockInfo.enabled) {
      _idleMonitor = IdleMonitor(
        timeout: Duration(minutes: _autoLockInfo.minutes),
        onIdle: _onIdle,
      );
    }

    _rotateIconController = RotateIconController();
    _children = [
      const GoDashboard(),
      const GoNetworks(),
      const GoSecurity(),
      if (AppConfig.hasFeature(AppFeature.swap) && Constants.enableExchange)
        const ExchangeView(),
      if (AppConfig.hasFeature(AppFeature.buy) && Constants.enableExchange)
        const BuyView(),
    ];

    ref.read(notificationsProvider).startCheckingWatchedNotifications();

    // WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
    //   showOneTimeTorHasBeenAddedDialogIfRequired(context);
    // });

    _idleMonitor?.attach();

    ref.read(prefsChangeNotifierProvider).addListener(_prefsTimeoutListener);

    super.initState();
  }

  @override
  dispose() {
    WidgetsBinding.instance.removeObserver(this);
    _prefs.removeListener(_prefsTimeoutListener);
    _idleMonitor?.detach();
    _rotateIconController.forward = null;
    _rotateIconController.reverse = null;
    _rotateIconController.reset = null;
    super.dispose();
  }

  DateTime _hiddenTime = DateTime.now();
  int _hiddenCount = 0;

  void _hiddenOptions() {
    _rotateIconController.reset?.call();
    _rotateIconController.forward?.call();
    if (_hiddenCount == 5) {
      Navigator.of(context).pushNamed(HiddenSettings.routeName);
    }
    final now = DateTime.now();
    const timeout = Duration(seconds: 1);
    if (now.difference(_hiddenTime) < timeout) {
      _hiddenCount++;
    } else {
      _hiddenCount = 0;
    }
    _hiddenTime = now;
  }

  @override
  Widget build(BuildContext context) {
    debugPrint("BUILD: $runtimeType");

    // dirty hack
    ref.listen(
      prefsChangeNotifierProvider.select((value) => value.enableExchange),
      (prev, next) {
        if (next == false &&
            mounted &&
            ref.read(homeViewPageIndexStateProvider) != 0) {
          WidgetsBinding.instance.addPostFrameCallback(
            (_) => ref.read(homeViewPageIndexStateProvider.state).state = 0,
          );
        }
      },
    );

    return WillPopScope(
      onWillPop: _onWillPop,
      child: Background(
        child: Scaffold(
          backgroundColor: Colors.transparent,
          key: _key,
          drawer: GoCoinDrawer(
            onOpen: (holding) {
              _key.currentState?.closeDrawer();
              openWalletGroup(context, ref, holding.coin, holding.walletCount);
            },
            onAdd: (coin) {
              _key.currentState?.closeDrawer();
              goAddCoin(context, coin);
            },
          ),
          appBar: AppBar(
            automaticallyImplyLeading: false,
            backgroundColor: Theme.of(
              context,
            ).extension<StackColors>()!.backgroundAppBar,
            title: Row(
              children: [
                IconButton(
                  key: const Key('goCoinDrawerButton'),
                  tooltip: goTr(context, '打开币种导航'),
                  onPressed: () => _key.currentState?.openDrawer(),
                  icon: const GoMark(size: 34),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Text(
                    goTr(context, "GOwallet"),
                    maxLines: 1,
                    overflow: TextOverflow.ellipsis,
                    style: STextStyles.navBarTitle(
                      context,
                    ).copyWith(fontWeight: FontWeight.w800),
                  ),
                ),
              ],
            ),
            actions: [
              if (AppConfig.hasFeature(AppFeature.tor))
                const Padding(
                  padding: EdgeInsets.only(top: 10, bottom: 10, right: 10),
                  child: AspectRatio(aspectRatio: 1, child: SmallTorIcon()),
                ),
              Padding(
                padding: const EdgeInsets.only(top: 10, bottom: 10, right: 10),
                child: AspectRatio(
                  aspectRatio: 1,
                  child: AppBarIconButton(
                    semanticsLabel: goTr(
                      context,
                      "Notifications Button. Takes To Notifications Page.",
                    ),
                    key: const Key("walletsViewAlertsButton"),
                    size: 36,
                    shadows: const [],
                    color: Theme.of(
                      context,
                    ).extension<StackColors>()!.backgroundAppBar,
                    icon: Platform.isIOS
                        ? Icon(
                            ref.watch(
                                  notificationsProvider.select(
                                    (value) => value.hasUnreadNotifications,
                                  ),
                                )
                                ? CupertinoIcons.bell_fill
                                : CupertinoIcons.bell,
                            size: 20,
                            color: Theme.of(
                              context,
                            ).extension<StackColors>()!.topNavIconPrimary,
                          )
                        : ref.watch(
                            notificationsProvider.select(
                              (value) => value.hasUnreadNotifications,
                            ),
                          )
                        ? SvgPicture.file(
                            File(
                              ref.watch(
                                themeProvider.select(
                                  (value) => value.assets.bellNew,
                                ),
                              ),
                            ),
                            width: 20,
                            height: 20,
                            color:
                                ref.watch(
                                  notificationsProvider.select(
                                    (value) => value.hasUnreadNotifications,
                                  ),
                                )
                                ? null
                                : Theme.of(
                                    context,
                                  ).extension<StackColors>()!.topNavIconPrimary,
                          )
                        : SvgPicture.asset(
                            Assets.svg.bell,
                            width: 20,
                            height: 20,
                            color:
                                ref.watch(
                                  notificationsProvider.select(
                                    (value) => value.hasUnreadNotifications,
                                  ),
                                )
                                ? null
                                : Theme.of(
                                    context,
                                  ).extension<StackColors>()!.topNavIconPrimary,
                          ),
                    onPressed: () {
                      // reset unread state
                      ref.refresh(unreadNotificationsStateProvider);

                      Navigator.of(
                        context,
                      ).pushNamed(NotificationsView.routeName).then((_) {
                        final Set<int> unreadNotificationIds = ref
                            .read(unreadNotificationsStateProvider.state)
                            .state;
                        if (unreadNotificationIds.isEmpty) return;

                        final List<Future<void>> futures = [];
                        for (
                          int i = 0;
                          i < unreadNotificationIds.length - 1;
                          i++
                        ) {
                          futures.add(
                            ref
                                .read(notificationsProvider)
                                .markAsRead(
                                  unreadNotificationIds.elementAt(i),
                                  false,
                                ),
                          );
                        }

                        // wait for multiple to update if any
                        Future.wait(futures).then((_) {
                          // only notify listeners once
                          ref
                              .read(notificationsProvider)
                              .markAsRead(unreadNotificationIds.last, true);
                        });
                      });
                    },
                  ),
                ),
              ),
              Padding(
                padding: const EdgeInsets.only(top: 10, bottom: 10, right: 10),
                child: AspectRatio(
                  aspectRatio: 1,
                  child: AppBarIconButton(
                    semanticsLabel: goTr(
                      context,
                      "Settings Button. Takes To Settings Page.",
                    ),
                    key: const Key("walletsViewSettingsButton"),
                    size: 36,
                    shadows: const [],
                    color: Theme.of(
                      context,
                    ).extension<StackColors>()!.backgroundAppBar,
                    icon: adaptiveIcon(
                      Assets.svg.gear,
                      CupertinoIcons.gear_solid,
                      size: 20,
                      color: Theme.of(
                        context,
                      ).extension<StackColors>()!.topNavIconPrimary,
                    ),
                    onPressed: () {
                      //todo: check if print needed
                      // debugPrint("main view settings tapped");
                      Navigator.of(
                        context,
                      ).pushNamed(GlobalSettingsView.routeName);
                    },
                  ),
                ),
              ),
            ],
          ),
          bottomNavigationBar: NavigationBar(
            selectedIndex: ref
                .watch(homeViewPageIndexStateProvider)
                .clamp(0, 2),
            onDestinationSelected: (index) =>
                ref.read(homeViewPageIndexStateProvider.state).state = index,
            indicatorColor: GoPalette.mint.withValues(alpha: .22),
            destinations: [
              NavigationDestination(
                icon: Icon(Icons.account_balance_wallet_outlined),
                selectedIcon: Icon(Icons.account_balance_wallet_rounded),
                label: goTr(context, "钱包"),
              ),
              NavigationDestination(
                icon: Icon(Icons.hub_outlined),
                selectedIcon: Icon(Icons.hub_rounded),
                label: goTr(context, "网络"),
              ),
              NavigationDestination(
                icon: Icon(Icons.shield_outlined),
                selectedIcon: Icon(Icons.shield_rounded),
                label: goTr(context, "安全"),
              ),
            ],
          ),
          body: SafeArea(
            child: Column(
              children: [
                if (AppConfig.hasFeature(AppFeature.swap) &&
                    _children.length > 1 &&
                    ref.watch(prefsChangeNotifierProvider).enableExchange)
                  Container(
                    decoration: BoxDecoration(
                      color: Theme.of(
                        context,
                      ).extension<StackColors>()!.backgroundAppBar,
                      boxShadow:
                          Theme.of(context)
                                  .extension<StackColors>()!
                                  .homeViewButtonBarBoxShadow !=
                              null
                          ? [
                              Theme.of(context)
                                  .extension<StackColors>()!
                                  .homeViewButtonBarBoxShadow!,
                            ]
                          : null,
                    ),
                    child: const Padding(
                      padding: EdgeInsets.only(
                        left: 16,
                        bottom: 12,
                        right: 16,
                        top: 0,
                      ),
                      child: HomeViewButtonBar(),
                    ),
                  ),
                Expanded(
                  // A single selection drives the bar and visible page,
                  // including when wallet recovery recreates HomeView.
                  child: IndexedStack(
                    index: ref.watch(homeViewPageIndexStateProvider).clamp(0, 2),
                    children: _children,
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
