/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:io';

import 'package:devicelocale/devicelocale.dart';
import 'package:flutter/material.dart';

class LocaleService extends ChangeNotifier {
  String _locale = "en_US"; // use default
  String? _appLocale;

  String get locale => _locale;

  void setAppLanguage(String language, {bool notify = true}) {
    final next = language == 'English (US)' ? 'en_US' : 'zh_CN';
    _appLocale = next;
    if (_locale == next) return;
    _locale = next;
    if (notify) notifyListeners();
  }

  Future<void> loadLocale({bool notify = true}) async {
    final deviceLocale =
        _appLocale ??
        (Platform.isWindows
            ? "en_US"
            : (await Devicelocale.currentAsLocale)?.toString() ?? "en_US");
    // An explicit app choice also wins if it changes during the platform call.
    _locale = _appLocale ?? deviceLocale;
    if (notify) {
      notifyListeners();
    }
  }
}
