import 'package:bitfinite/gowallet/l10n/go_localizations.dart';
/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/material.dart';
import 'package:flutter_svg/svg.dart';
import '../../../../themes/stack_colors.dart';
import '../../../../utilities/assets.dart';
import '../../../../utilities/text_styles.dart';
import '../../../../utilities/util.dart';
import '../../../../widgets/desktop/desktop_dialog.dart';
import '../../../../widgets/desktop/desktop_dialog_close_button.dart';
import '../../../../widgets/desktop/primary_button.dart';
import '../../../../widgets/stack_dialog.dart';

class RestoreSucceededDialog extends StatelessWidget {
  const RestoreSucceededDialog({super.key});

  @override
  Widget build(BuildContext context) {
    if (Util.isDesktop) {
      return DesktopDialog(
        child: Column(
          children: [
            const DesktopDialogCloseButton(),
            const Spacer(flex: 1),
            SvgPicture.asset(
              Assets.svg.checkCircle,
              width: 40,
              height: 40,
              color: Theme.of(
                context,
              ).extension<StackColors>()!.accentColorDark,
            ),
            const Spacer(flex: 2),
            Text(
              goTr(context, "钱包恢复成功"),
              style: STextStyles.desktopH2(context),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 16),
            Text(
              goTr(context, "现在可以查看你的钱包。"),
              style: STextStyles.desktopTextMedium(context).copyWith(
                color: Theme.of(context).extension<StackColors>()!.textDark3,
              ),
              textAlign: TextAlign.center,
            ),
            const Spacer(flex: 2),
            Padding(
              padding: const EdgeInsets.only(left: 32, right: 32, bottom: 32),
              child: PrimaryButton(
                width: 272.5,
                label: goTr(context, "OK"),
                onPressed: () {
                  Navigator.of(context).pop();
                },
              ),
            ),
          ],
        ),
      );
    } else {
      return StackDialog(
        title: goTr(context, "钱包恢复成功"),
        message: goTr(context, "现在可以查看你的钱包。"),
        icon: SvgPicture.asset(
          Assets.svg.checkCircle,
          width: 24,
          height: 24,
          color: Theme.of(context).extension<StackColors>()!.accentColorGreen,
        ),
        rightButton: TextButton(
          style: Theme.of(
            context,
          ).extension<StackColors>()!.getSecondaryEnabledButtonStyle(context),
          child: Text(
            goTr(context, "确定"),
            style: STextStyles.itemSubtitle12(context),
          ),
          onPressed: () {
            Navigator.of(context).pop();
          },
        ),
      );
    }
  }
}
