import 'package:bitfinite/gowallet/l10n/go_localizations.dart';
/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:package_info_plus/package_info_plus.dart';
import 'package:url_launcher/url_launcher.dart';

import '../../../app_config.dart';
import '../../../themes/stack_colors.dart';
import '../../../utilities/git_status.dart';
import '../../../utilities/text_styles.dart';
import '../../../wallets/crypto_currency/crypto_currency.dart';
import '../../../widgets/background.dart';
import '../../../widgets/custom_buttons/app_bar_icon_button.dart';
import '../../../widgets/custom_buttons/blue_text_button.dart';
import '../../../widgets/rounded_white_container.dart';

class AboutView extends ConsumerWidget {
  const AboutView({super.key});

  static const String routeName = "/about";

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Background(
      child: Scaffold(
        backgroundColor: Theme.of(context).extension<StackColors>()!.background,
        appBar: AppBar(
          leading: AppBarBackButton(
            onPressed: () async {
              Navigator.of(context).pop();
            },
          ),
          title: Text(
            goTr(context, "About"),
            style: STextStyles.navBarTitle(context),
          ),
        ),
        body: SafeArea(
          child: Padding(
            padding: const EdgeInsets.all(16),
            child: LayoutBuilder(
              builder: (context, constraints) {
                return SingleChildScrollView(
                  child: ConstrainedBox(
                    constraints: BoxConstraints(
                      minHeight: constraints.maxHeight,
                    ),
                    child: IntrinsicHeight(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.stretch,
                        children: [
                          FutureBuilder(
                            future: PackageInfo.fromPlatform(),
                            builder:
                                (context, AsyncSnapshot<PackageInfo> snapshot) {
                                  String version = "";
                                  String signature = "";
                                  String appName = "";
                                  String build = "";

                                  if (snapshot.connectionState ==
                                          ConnectionState.done &&
                                      snapshot.hasData) {
                                    version = snapshot.data!.version;
                                    build = snapshot.data!.buildNumber;
                                    signature = snapshot.data!.buildSignature;
                                    appName = snapshot.data!.appName;
                                  }

                                  return Column(
                                    crossAxisAlignment:
                                        CrossAxisAlignment.stretch,
                                    children: [
                                      Center(
                                        child: Text(
                                          appName,
                                          style: STextStyles.pageTitleH2(
                                            context,
                                          ),
                                        ),
                                      ),
                                      const SizedBox(height: 24),
                                      RoundedWhiteContainer(
                                        child: Column(
                                          crossAxisAlignment:
                                              CrossAxisAlignment.stretch,
                                          children: [
                                            Text(
                                              goTr(context, "Version"),
                                              style: STextStyles.titleBold12(
                                                context,
                                              ),
                                            ),
                                            const SizedBox(height: 4),
                                            SelectableText(
                                              version,
                                              style: STextStyles.itemSubtitle(
                                                context,
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                      const SizedBox(height: 12),
                                      RoundedWhiteContainer(
                                        child: Column(
                                          crossAxisAlignment:
                                              CrossAxisAlignment.stretch,
                                          children: [
                                            Text(
                                              goTr(context, "Build number"),
                                              style: STextStyles.titleBold12(
                                                context,
                                              ),
                                            ),
                                            const SizedBox(height: 4),
                                            SelectableText(
                                              build,
                                              style: STextStyles.itemSubtitle(
                                                context,
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                      const SizedBox(height: 12),
                                      RoundedWhiteContainer(
                                        child: Column(
                                          crossAxisAlignment:
                                              CrossAxisAlignment.stretch,
                                          children: [
                                            Text(
                                              goTr(context, "Build commit"),
                                              style: STextStyles.titleBold12(
                                                context,
                                              ),
                                            ),
                                            const SizedBox(height: 4),
                                            SelectableText(
                                              GitStatus.appCommitHash,
                                              style: STextStyles.itemSubtitle(
                                                context,
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                      const SizedBox(height: 12),
                                      RoundedWhiteContainer(
                                        child: Column(
                                          crossAxisAlignment:
                                              CrossAxisAlignment.stretch,
                                          children: [
                                            Text(
                                              goTr(context, "Build signature"),
                                              style: STextStyles.titleBold12(
                                                context,
                                              ),
                                            ),
                                            const SizedBox(height: 4),
                                            SelectableText(
                                              signature,
                                              style: STextStyles.itemSubtitle(
                                                context,
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ],
                                  );
                                },
                          ),
                          if (AppConfig.coins.whereType<Epiccash>().isNotEmpty)
                            const SizedBox(height: 12),
                          if (AppConfig.coins.whereType<Epiccash>().isNotEmpty)
                            FutureBuilder(
                              future: GitStatus.getEpicCommitStatus(),
                              builder:
                                  (
                                    context,
                                    AsyncSnapshot<CommitStatus> snapshot,
                                  ) {
                                    CommitStatus stateOfCommit =
                                        CommitStatus.notLoaded;

                                    if (snapshot.connectionState ==
                                            ConnectionState.done &&
                                        snapshot.hasData) {
                                      stateOfCommit = snapshot.data!;
                                    }

                                    return RoundedWhiteContainer(
                                      child: Column(
                                        crossAxisAlignment:
                                            CrossAxisAlignment.stretch,
                                        children: [
                                          Text(
                                            goTr(
                                              context,
                                              "Epic Cash Build Commit",
                                            ),
                                            style: STextStyles.titleBold12(
                                              context,
                                            ),
                                          ),
                                          const SizedBox(height: 4),
                                          SelectableText(
                                            GitStatus.epicCashCommit,
                                            style: GitStatus.styleForStatus(
                                              stateOfCommit,
                                              context,
                                            ),
                                          ),
                                        ],
                                      ),
                                    );
                                  },
                            ),
                          const SizedBox(height: 12),
                          if (AppConfig.coins
                              .whereType<Mimblewimblecoin>()
                              .isNotEmpty)
                            const SizedBox(height: 12),
                          if (AppConfig.coins
                              .whereType<Mimblewimblecoin>()
                              .isNotEmpty)
                            FutureBuilder(
                              future:
                                  GitStatus.getMimblewimblecoinCommitStatus(),
                              builder:
                                  (
                                    context,
                                    AsyncSnapshot<CommitStatus> snapshot,
                                  ) {
                                    CommitStatus stateOfCommit =
                                        CommitStatus.notLoaded;

                                    if (snapshot.connectionState ==
                                            ConnectionState.done &&
                                        snapshot.hasData) {
                                      stateOfCommit = snapshot.data!;
                                    }

                                    return RoundedWhiteContainer(
                                      child: Column(
                                        crossAxisAlignment:
                                            CrossAxisAlignment.stretch,
                                        children: [
                                          Text(
                                            goTr(
                                              context,
                                              "Mimblewimblecoin Build Commit",
                                            ),
                                            style: STextStyles.titleBold12(
                                              context,
                                            ),
                                          ),
                                          const SizedBox(height: 4),
                                          SelectableText(
                                            GitStatus.mimblewimblecoinCommit,
                                            style: GitStatus.styleForStatus(
                                              stateOfCommit,
                                              context,
                                            ),
                                          ),
                                        ],
                                      ),
                                    );
                                  },
                            ),
                          if (AppConfig.coins.whereType<Monero>().isNotEmpty)
                            const SizedBox(height: 12),
                          // if (AppConfig.coins.whereType<Monero>().isNotEmpty)
                          //   FutureBuilder(
                          //     future: GitStatus.getMoneroCommitStatus(),
                          //     builder: (
                          //       context,
                          //       AsyncSnapshot<CommitStatus> snapshot,
                          //     ) {
                          //       CommitStatus stateOfCommit =
                          //           CommitStatus.notLoaded;
                          //
                          //       if (snapshot.connectionState ==
                          //               ConnectionState.done &&
                          //           snapshot.hasData) {
                          //         stateOfCommit = snapshot.data!;
                          //       }
                          //       return RoundedWhiteContainer(
                          //         child: Column(
                          //           crossAxisAlignment:
                          //               CrossAxisAlignment.stretch,
                          //           children: [
                          //             Text(
                          //               "Monero Build Commit",
                          //               style: STextStyles.titleBold12(context),
                          //             ),
                          //             const SizedBox(
                          //               height: 4,
                          //             ),
                          //             SelectableText(
                          //               GitStatus.moneroCommit,
                          //               style: GitStatus.styleForStatus(
                          //                 stateOfCommit,
                          //                 context,
                          //               ),
                          //             ),
                          //           ],
                          //         ),
                          //       );
                          //     },
                          //   ),
                          // const SizedBox(
                          //   height: 12,
                          // ),
                          RoundedWhiteContainer(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(
                                  goTr(context, "开源来源与致谢"),
                                  style: STextStyles.titleBold12(context),
                                ),
                                const SizedBox(height: 8),
                                Text(
                                  goTr(
                                    context,
                                    'GOwallet 使用的源代码来源于 Stack Wallet 开源项目，并在此基础上进行二次开发和完善。感谢 Stack Wallet / Cypher Stack 提供开源代码。',
                                  ),
                                  style: STextStyles.label(
                                    context,
                                  ).copyWith(height: 1.5),
                                ),
                                const SizedBox(height: 8),
                                CustomTextButton(
                                  text:
                                      "https://github.com/cypherstack/stack_wallet",
                                  onTap: () {
                                    launchUrl(
                                      Uri.parse(
                                        "https://github.com/cypherstack/stack_wallet",
                                      ),
                                      mode: LaunchMode.externalApplication,
                                    );
                                  },
                                ),
                              ],
                            ),
                          ),
                          const SizedBox(height: 8),
                          CustomTextButton(
                            text: goTr(context, 'GPLv3 许可与完整来源记录'),
                            onTap: () => launchUrl(
                              Uri.parse(
                                'https://github.com/AlexZeroZero/GOwallet/blob/main/NOTICE.md',
                              ),
                              mode: LaunchMode.externalApplication,
                            ),
                          ),
                          if (AppConfig.coins.whereType<Tezos>().isNotEmpty)
                            const SizedBox(height: 12),
                          if (AppConfig.coins.whereType<Tezos>().isNotEmpty)
                            RoundedWhiteContainer(
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    goTr(context, "Upstream source"),
                                    style: STextStyles.titleBold12(context),
                                  ),
                                  const SizedBox(height: 4),
                                  CustomTextButton(
                                    text:
                                        "https://github.com/cypherstack/stack_wallet",
                                    onTap: () {
                                      launchUrl(
                                        Uri.parse(
                                          "https://github.com/cypherstack/stack_wallet",
                                        ),
                                        mode: LaunchMode.externalApplication,
                                      );
                                    },
                                  ),
                                ],
                              ),
                            ),
                          if (AppConfig.coins.whereType<Tezos>().isNotEmpty)
                            const SizedBox(height: 12),
                          if (AppConfig.coins.whereType<Tezos>().isNotEmpty)
                            RoundedWhiteContainer(
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    goTr(context, "Tezos functionality"),
                                    style: STextStyles.titleBold12(context),
                                  ),
                                  const SizedBox(height: 4),
                                  CustomTextButton(
                                    text: goTr(context, "Powered by TzKT API"),
                                    onTap: () {
                                      launchUrl(
                                        Uri.parse("https://tzkt.io"),
                                        mode: LaunchMode.externalApplication,
                                      );
                                    },
                                  ),
                                ],
                              ),
                            ),
                          const SizedBox(height: 12),
                          const Spacer(),
                          Text(
                            goTr(
                              context,
                              "GOwallet is a non-custodial wallet. Keys stay on your device. Electrum nodes are operated by third parties or project teams; their availability is outside GOwallet’s control. Servers receive address queries and signed transactions. TCP is unencrypted; compatible servers support TLS.",
                            ),
                            textAlign: TextAlign.center,
                            style: STextStyles.label(context),
                          ),
                        ],
                      ),
                    ),
                  ),
                );
              },
            ),
          ),
        ),
      ),
    );
  }
}
