import 'package:bitfinite/gowallet/l10n/go_localizations.dart';
/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../app_config.dart';
import '../../../providers/providers.dart';
import '../../../route_generator.dart';
import '../../../themes/stack_colors.dart';
import '../../../utilities/assets.dart';
import '../../../utilities/text_styles.dart';
import '../../../widgets/background.dart';
import '../../../widgets/custom_buttons/app_bar_icon_button.dart';
import '../../../widgets/rounded_white_container.dart';
import '../../address_book_views/address_book_view.dart';
import '../../pinpad_views/lock_screen_view.dart';
import '../../shopinbit/shopinbit_settings_view.dart';
import '../sub_widgets/settings_list_button.dart';
import 'about_view.dart';
import 'advanced_views/advanced_settings_view.dart';
import 'appearance_settings/appearance_settings_view.dart';
import 'currency_view.dart';
import 'delete_account_view.dart';
import 'language_view.dart';
import 'manage_nodes_views/manage_nodes_view.dart';
import 'security_views/security_view.dart';
import 'stack_backup_views/stack_backup_view.dart';
import 'startup_preferences/startup_preferences_view.dart';
import 'support_view.dart';
import 'syncing_preferences_views/syncing_preferences_view.dart';
import 'tor_settings/tor_settings_view.dart';

class GlobalSettingsView extends StatelessWidget {
  const GlobalSettingsView({super.key});

  static const String routeName = "/globalSettings";

  @override
  Widget build(BuildContext context) {
    debugPrint("BUILD: $runtimeType");
    return Background(
      child: Scaffold(
        backgroundColor: Theme.of(context).extension<StackColors>()!.background,
        appBar: AppBar(
          leading: AppBarBackButton(
            onPressed: () {
              Navigator.of(context).pop();
            },
          ),
          title: Text(
            goTr(context, "设置"),
            style: STextStyles.navBarTitle(context),
          ),
        ),
        body: SafeArea(
          child: LayoutBuilder(
            builder: (builderContext, constraints) {
              return Padding(
                padding: const EdgeInsets.only(left: 12, top: 12, right: 12),
                child: SingleChildScrollView(
                  child: ConstrainedBox(
                    constraints: BoxConstraints(
                      minHeight: constraints.maxHeight - 24,
                    ),
                    child: IntrinsicHeight(
                      child: Padding(
                        padding: const EdgeInsets.all(4),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.stretch,
                          children: [
                            RoundedWhiteContainer(
                              padding: const EdgeInsets.all(4),
                              child: Column(
                                children: [
                                  SettingsListButton(
                                    iconAssetName: Assets.svg.addressBook,
                                    iconSize: 16,
                                    title: goTr(context, "地址簿"),
                                    onPressed: () {
                                      Navigator.of(
                                        context,
                                      ).pushNamed(AddressBookView.routeName);
                                    },
                                  ),
                                  const SizedBox(height: 8),
                                  SettingsListButton(
                                    iconAssetName: Assets.svg.downloadFolder,
                                    iconSize: 14,
                                    title: goTr(
                                      context,
                                      "{0} backup & restore",
                                      [AppConfig.prefix],
                                    ),
                                    onPressed: () {
                                      Navigator.push(
                                        context,
                                        RouteGenerator.getRoute(
                                          shouldUseMaterialRoute: RouteGenerator
                                              .useMaterialPageRoute,
                                          builder: (_) => LockscreenView(
                                            showBackButton: true,
                                            routeOnSuccess:
                                                StackBackupView.routeName,
                                            biometricsCancelButtonString: goTr(
                                              context,
                                              "CANCEL",
                                            ),
                                            biometricsLocalizedReason: goTr(
                                              context,
                                              "Authenticate to access {0} backup & restore settings",
                                              [AppConfig.prefix],
                                            ),
                                            biometricsAuthenticationTitle: goTr(
                                              context,
                                              "{0} backup",
                                              [AppConfig.prefix],
                                            ),
                                          ),
                                          settings: const RouteSettings(
                                            name: "/swblockscreen",
                                          ),
                                        ),
                                      );
                                    },
                                  ),
                                  const SizedBox(height: 8),
                                  SettingsListButton(
                                    iconAssetName: Assets.svg.lock,
                                    iconSize: 16,
                                    title: goTr(context, "安全设置"),
                                    onPressed: () {
                                      Navigator.of(
                                        context,
                                      ).pushNamed(SecurityView.routeName);
                                    },
                                  ),
                                  const SizedBox(height: 8),
                                  SettingsListButton(
                                    iconAssetName: Assets.svg.dollarSign,
                                    iconSize: 18,
                                    title: goTr(context, "Currency"),
                                    onPressed: () {
                                      Navigator.of(context).pushNamed(
                                        BaseCurrencySettingsView.routeName,
                                      );
                                    },
                                  ),
                                  const SizedBox(height: 8),
                                  SettingsListButton(
                                    iconAssetName: Assets.svg.language,
                                    iconSize: 18,
                                    title: goTr(context, "Language"),
                                    onPressed: () {
                                      Navigator.of(context).pushNamed(
                                        LanguageSettingsView.routeName,
                                      );
                                    },
                                  ),
                                  const SizedBox(height: 8),
                                  SettingsListButton(
                                    iconAssetName: Assets.svg.tor,
                                    iconSize: 18,
                                    title: goTr(context, "Tor Settings"),
                                    onPressed: () {
                                      Navigator.of(
                                        context,
                                      ).pushNamed(TorSettingsView.routeName);
                                    },
                                  ),
                                  const SizedBox(height: 8),
                                  SettingsListButton(
                                    iconAssetName: Assets.svg.node,
                                    iconSize: 16,
                                    title: goTr(context, "Manage nodes"),
                                    onPressed: () {
                                      Navigator.of(
                                        context,
                                      ).pushNamed(ManageNodesView.routeName);
                                    },
                                  ),
                                  const SizedBox(height: 8),
                                  SettingsListButton(
                                    iconAssetName: Assets.svg.arrowRotate,
                                    iconSize: 18,
                                    title: goTr(context, "同步偏好"),
                                    onPressed: () {
                                      Navigator.of(context).pushNamed(
                                        SyncingPreferencesView.routeName,
                                      );
                                    },
                                  ),
                                  const SizedBox(height: 8),
                                  SettingsListButton(
                                    iconAssetName: Assets.svg.arrowUpRight,
                                    iconSize: 16,
                                    title: goTr(context, "Startup"),
                                    onPressed: () {
                                      Navigator.of(context).pushNamed(
                                        StartupPreferencesView.routeName,
                                      );
                                    },
                                  ),
                                  if (AppConfig.hasFeature(
                                    AppFeature.themeSelection,
                                  ))
                                    const SizedBox(height: 8),
                                  if (AppConfig.hasFeature(
                                    AppFeature.themeSelection,
                                  ))
                                    SettingsListButton(
                                      iconAssetName: Assets.svg.sun,
                                      iconSize: 18,
                                      title: goTr(context, "Appearance"),
                                      onPressed: () {
                                        Navigator.of(context).pushNamed(
                                          AppearanceSettingsView.routeName,
                                        );
                                      },
                                    ),
                                  if (Platform.isIOS) const SizedBox(height: 8),
                                  if (Platform.isIOS)
                                    SettingsListButton(
                                      iconAssetName: Assets.svg.circleAlert,
                                      iconSize: 16,
                                      title: goTr(context, "Delete account"),
                                      onPressed: () async {
                                        await Navigator.of(context).pushNamed(
                                          DeleteAccountView.routeName,
                                        );
                                      },
                                    ),
                                  const SizedBox(height: 8),
                                  SettingsListButton(
                                    iconAssetName: Assets.svg.ellipsis,
                                    iconSize: 18,
                                    title: goTr(context, "About"),
                                    onPressed: () {
                                      Navigator.of(
                                        context,
                                      ).pushNamed(AboutView.routeName);
                                    },
                                  ),
                                  const SizedBox(height: 8),
                                  SettingsListButton(
                                    iconAssetName: Assets.svg.solidSliders,
                                    iconSize: 16,
                                    title: goTr(context, "高级选项"),
                                    onPressed: () {
                                      Navigator.of(context).pushNamed(
                                        AdvancedSettingsView.routeName,
                                      );
                                    },
                                  ),
                                  if (AppConfig.hasFeature(
                                    AppFeature.shopinBit,
                                  ))
                                    Consumer(
                                      builder: (_, ref, __) {
                                        final familiarity = ref.watch(
                                          prefsChangeNotifierProvider.select(
                                            (v) => v.familiarity,
                                          ),
                                        );
                                        if (familiarity < 6) {
                                          return const SizedBox.shrink();
                                        }
                                        return Column(
                                          children: [
                                            const SizedBox(height: 8),
                                            SettingsListButton(
                                              iconAssetName: Assets.svg.key,
                                              iconSize: 16,
                                              title: goTr(context, "ShopinBit"),
                                              onPressed: () {
                                                Navigator.of(context).pushNamed(
                                                  ShopInBitSettingsView
                                                      .routeName,
                                                );
                                              },
                                            ),
                                          ],
                                        );
                                      },
                                    ),
                                  const SizedBox(height: 8),
                                  SettingsListButton(
                                    iconAssetName: Assets.svg.questionMessage,
                                    iconSize: 16,
                                    title: goTr(context, "Support"),
                                    onPressed: () {
                                      Navigator.of(
                                        context,
                                      ).pushNamed(SupportView.routeName);
                                    },
                                  ),
                                  // TextButton(
                                  //   style: Theme.of(context)
                                  //       .textButtonTheme
                                  //       .style
                                  //       ?.copyWith(
                                  //         backgroundColor:
                                  //             MaterialStateProperty.all<Color>(
                                  //           Theme.of(context).extension<StackColors>()!.accentColorDark
                                  //         ),
                                  //       ),
                                  //   child: Text(
                                  //     "fire test notification",
                                  //     style: STextStyles.button(context),
                                  //   ),
                                  //   onPressed: () async {
                                  //     NotificationApi.showNotification2(
                                  //       title: "Test notification",
                                  //       body: "My doggy wallet",
                                  //       walletId:
                                  //           "3c5e2d70-fcc3-11ec-86a3-31a106a81c3b",
                                  //       iconAssetName:
                                  //           Assets.svg.iconFor(coin: Coin.dogecoin),
                                  //       date: DateTime.now(),
                                  //     );
                                  //   },
                                  // ),
                                ],
                              ),
                            ),
                            const SizedBox(height: 12),
                          ],
                        ),
                      ),
                    ),
                  ),
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}
