import 'package:bitfinite/gowallet/l10n/go_localizations.dart';
/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../themes/coin_image_provider.dart';
import '../../../themes/stack_colors.dart';
import '../../../utilities/assets.dart';
import '../../../utilities/text_styles.dart';
import '../../../utilities/util.dart';
import '../../../wallets/crypto_currency/crypto_currency.dart';
import '../../../widgets/desktop/desktop_dialog.dart';
import '../../../widgets/stack_dialog.dart';

class SendingTransactionDialog extends ConsumerStatefulWidget {
  const SendingTransactionDialog({
    super.key,
    required this.coin,
    required this.controller,
  });

  final CryptoCurrency coin;
  final ProgressAndSuccessController controller;

  @override
  ConsumerState<SendingTransactionDialog> createState() =>
      _RestoringDialogState();
}

class _RestoringDialogState extends ConsumerState<SendingTransactionDialog> {
  late ProgressAndSuccessController? _progressAndSuccessController;

  @override
  void initState() {
    _progressAndSuccessController = widget.controller;

    super.initState();
  }

  @override
  void dispose() {
    _progressAndSuccessController = null;

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final assetPath = ref.watch(coinImageSecondaryProvider(widget.coin));

    if (Util.isDesktop) {
      return DesktopDialog(
        maxHeight: assetPath.endsWith(".gif") ? double.infinity : null,
        child: Padding(
          padding: const EdgeInsets.all(40),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(
                goTr(context, "Sending transaction"),
                style: STextStyles.desktopH3(context),
              ),
              const SizedBox(height: 40),
              assetPath.endsWith(".gif")
                  ? Flexible(child: Image.file(File(assetPath)))
                  : ProgressAndSuccess(
                      controller: _progressAndSuccessController!,
                    ),
            ],
          ),
        ),
      );
    } else {
      return WillPopScope(
        onWillPop: () async {
          return false;
        },
        child: assetPath.endsWith(".gif")
            ? StackDialogBase(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Image.file(File(assetPath)),
                    Text(
                      goTr(context, "Sending transaction"),
                      textAlign: TextAlign.center,
                      style: STextStyles.pageTitleH2(context),
                    ),
                    const SizedBox(height: 32),
                  ],
                ),
              )
            : StackDialog(
                title: goTr(context, "Sending transaction"),
                icon: ProgressAndSuccess(
                  controller: _progressAndSuccessController!,
                ),
              ),
      );
    }
  }
}

class ProgressAndSuccessController {
  VoidCallback? triggerSuccess;
}

class ProgressAndSuccess extends StatefulWidget {
  const ProgressAndSuccess({
    super.key,
    this.height = 24,
    this.width = 24,
    required this.controller,
  });

  final double height;
  final double width;
  final ProgressAndSuccessController controller;

  @override
  State<ProgressAndSuccess> createState() => _ProgressAndSuccessState();
}

class _ProgressAndSuccessState extends State<ProgressAndSuccess> {
  bool _success = false;
  void _complete() {
    if (mounted) setState(() => _success = true);
  }

  @override
  void initState() {
    super.initState();
    widget.controller.triggerSuccess = _complete;
  }

  @override
  void didUpdateWidget(ProgressAndSuccess oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.controller != widget.controller) {
      oldWidget.controller.triggerSuccess = null;
      widget.controller.triggerSuccess = _complete;
    }
  }

  @override
  void dispose() {
    widget.controller.triggerSuccess = null;
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => SizedBox(
    width: widget.width,
    height: widget.height,
    child: _success
        ? Icon(
            Icons.check_circle_rounded,
            size: widget.height,
            color: Theme.of(context).colorScheme.primary,
          )
        : CircularProgressIndicator(
            strokeWidth: 2.5,
            value: MediaQuery.disableAnimationsOf(context) ? .7 : null,
          ),
  );
}
