"""Configure the Android GOwallet flavor from the upstream templates."""
from pathlib import Path
import shutil
import subprocess
from build_go_themes import build_go_themes
from go_brand_assets import write_brand_assets

ROOT = Path(__file__).resolve().parents[1]
TEMPLATES = ROOT / 'scripts/app_config/templates'


def write(path, text):
    dest = ROOT / path
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(text, encoding='utf-8', newline='\n')


def main():
    pubspec = (TEMPLATES / 'pubspec.template.yaml').read_text(encoding='utf-8')
    # Keep the Dart package name for compatibility with upstream test imports.
    pubspec = pubspec.replace('name: PLACEHOLDER', 'name: bitfinite')
    pubspec = pubspec.replace('description: PLACEHOLDER', 'description: GOwallet for small PoW coins')
    pubspec = pubspec.replace('PLACEHOLDER_V+PLACEHOLDER_B', '1.0.3+12')
    pubspec = pubspec.replace(
        '  coinlib:\n    git:\n      url: https://github.com/cypherstack/coinlib\n      path: coinlib\n      ref: a3c972ce0b71b45afe17576d39831fe370ce7ce7',
        '  coinlib:\n    path: vendor/coinlib')
    pubspec = pubspec.replace('  coinlib_flutter:\n    git:\n      url: https://github.com/cypherstack/coinlib\n      path: coinlib_flutter\n      ref: a3c972ce0b71b45afe17576d39831fe370ce7ce7', '  coinlib_flutter:\n    path: vendor/coinlib_flutter')
    pubspec = pubspec.replace('  integration_test:\n      sdk: flutter\n', '')
    pubspec = pubspec.replace('  electrum_adapter:\n    git:\n      url: https://github.com/cypherstack/electrum_adapter.git\n      ref: b6fa44d015d3bfa06934b73219928c29ca48a290', '  electrum_adapter:\n    path: vendor/electrum_adapter')
    # Exclude inherited brand imagery and animations from this flavor's APK.
    pubspec = pubspec.replace('    - assets/in_app_logo_icons/', '    - assets/in_app_logo_icons/electrum-wallet.svg')
    for directory in ('assets/images/', 'assets/icon/', 'assets/gif/'):
        pubspec = pubspec.replace('    - ' + directory + '\n', '')
    pubspec = '\n'.join(line for line in pubspec.split('\n') if '    - assets/lottie/' not in line)
    write('pubspec.yaml', pubspec)
    dart = shutil.which('dart')
    if not dart:
        raise RuntimeError('Flutter/Dart SDK must be on PATH')
    subprocess.run([dart, str(ROOT / 'tool/gen_interfaces.dart'),
                    str(ROOT / 'tool/wl_templates'),
                    str(ROOT / 'lib/wl_gen/generated')], check=True, cwd=ROOT)
    try:
        commit = subprocess.check_output(
            ['git', 'rev-parse', 'HEAD'], cwd=ROOT, text=True,
            stderr=subprocess.DEVNULL).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        commit = 'v1.0.3-source-archive'
    write('lib/app_config.g.dart', f'''// Generated by tool/configure_electrum_wallet.py.
part of 'app_config.dart';
const _prefix = "GOwallet";
const _separator = "";
const _suffix = "";
const _emptyWalletsMessage = "Create or restore a wallet to get started.";
const _appDataDirName = "scash_shic_electrum_wallet";
const _shortDescriptionText = "小型 PoW 币种的自托管钱包。";
const _commitHash = "{commit}";
const _mwebdExeHash = "";
const Set<AppFeature> _features = {{AppFeature.themeSelection}};
const ({{String light, String dark}})? _appIconAsset = (
  light: 'assets/in_app_logo_icons/electrum-wallet.svg',
  dark: 'assets/in_app_logo_icons/electrum-wallet.svg',
);
final List<CryptoCurrency> _supportedCoins = List.unmodifiable([
  Scash(CryptoCurrencyNetwork.main),
  Shibacoin(CryptoCurrencyNetwork.main),
  Pepecoin(CryptoCurrencyNetwork.main),
  Dingocoin(CryptoCurrencyNetwork.main),
]);
final ({{String from, String fromFuzzyNet, String to, String toFuzzyNet}})
_swapDefaults = (from: "SCASH", fromFuzzyNet: "scash", to: "SHIC", toFuzzyNet: "shic");
''')
    for source in (TEMPLATES / 'android').rglob('*'):
        if source.is_file():
            content = source.read_text(encoding='utf-8')
            content = content.replace('com.place.holder', 'org.gowallet.pow')
            content = content.replace('PlaceHolderName', 'GOwallet')
            content = content.replace('@mipmap/ic_launcher', '@mipmap/gowallet_launcher')
            write(source.relative_to(TEMPLATES), content)
    # Notification icons are resolved by name at runtime. Keep the monochrome
    # GO mark explicitly so Android resource shrinking cannot remove it.
    (ROOT / 'android/app/src/main/res/drawable/app_icon_alpha.png').unlink(missing_ok=True)
    write('android/app/src/main/res/raw/gowallet_keep.xml', '<resources xmlns:tools="http://schemas.android.com/tools" tools:keep="@drawable/app_icon_alpha" />')
    for variant in ('drawable', 'drawable-v21', 'drawable-night', 'drawable-night-v21'):
        write(f'android/app/src/main/res/{variant}/launch_background.xml', '''<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item><shape><solid android:color="#122421"/></shape></item>
    <item android:width="104dp" android:height="104dp" android:gravity="center" android:drawable="@drawable/electrum_wallet_icon"/>
</layer-list>
''')
    for variant in ('values', 'values-night', 'values-v31', 'values-night-v31'):
        path = ROOT / 'android/app/src/main/res' / variant / 'styles.xml'
        if path.exists():
            write(path.relative_to(ROOT), path.read_text(encoding='utf-8')
                  .replace('@drawable/android12splash', '@drawable/go_splash_icon')
                  .replace('@drawable/electrum_wallet_icon', '@drawable/go_splash_icon')
                  .replace('#0644F1', '#122421')
                  .replace('#253855', '#122421')
                  .replace('?android:colorBackground', '#122421'))
    # Copy assets instead of requiring Windows symbolic-link privileges.
    for name in ('default_themes', 'icon', 'lottie', 'in_app_logo_icons', 'svg'):
        source = ROOT / 'asset_sources' / name / 'bitfinite'
        shutil.copytree(source, ROOT / 'assets' / name, dirs_exist_ok=True)
    shutil.copyfile(ROOT / 'tool/flavors/electrum_wallet.svg',
                    ROOT / 'assets/in_app_logo_icons/electrum-wallet.svg')
    write_brand_assets(ROOT)
    build_go_themes(ROOT)
    keys = ROOT / 'lib/external_api_keys.dart'
    if not keys.exists():
        names = ('ChangeNowApiKey', 'SimpleSwapApiKey', 'NanswapApiKey', 'NanoSwapRpcApiKey',
                 'WizSwapApiKey', 'ShopInBitAccessKey', 'ShopInBitPartnerSecret', 'CakePayApiToken', 'ExolixApiKey')
        write('lib/external_api_keys.dart', ''.join(f'const k{name} = "";\n' for name in names))
    print('Configured GOwallet: SCASH + SHIC + PEP + DINGO + custom Electrum coins, Android application ID org.gowallet.pow')


if __name__ == '__main__':
    main()
