/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../services/locale_service.dart';
import 'prefs_provider.dart';

int _count = 0;
final localeServiceChangeNotifierProvider =
    ChangeNotifierProvider<LocaleService>((ref) {
      if (kDebugMode) {
        _count++;
      }

      return LocaleService()..setAppLanguage(
        ref.watch(
          prefsChangeNotifierProvider.select((prefs) => prefs.language),
        ),
        notify: false,
      );
    });
