import { COINS, type CoinId } from './coins.js';
import { derive, newMnemonic, validMnemonic } from './wallet.js';
import { saveVault, loadVault, hasVault } from './vault.js';
import { ElectrumClient } from './electrum.js';
import { formatAmount } from './encoding.js';

let mnemonic = '';
let selected: CoinId = 'scash';
let client: ElectrumClient | undefined;
let activeTab = 'assets';
const $ = <T extends HTMLElement>(selector: string) => document.querySelector<T>(selector)!;
const english = () => localStorage.getItem('lang') === 'en';
const dark = () => localStorage.getItem('theme') !== 'light';
const t = (zh: string, en: string) => english() ? en : zh;

function header() {
  return `<header class="topbar"><div class="brand"><img src="assets/logo.svg" alt="GOwallet"><span>GOwallet</span></div><div class="header-actions"><button class="round-button" id="theme" title="${t('切换主题', 'Toggle theme')}">${dark() ? '◐' : '☼'}</button><button class="language" id="language">${english() ? '中文' : 'EN'}</button></div></header>`;
}
function footer() { return `<footer><span><b class="footer-dot"></b>${t('非托管 · 本地密钥', 'Non-custodial · Local keys')}</span><a href="https://github.com/AlexZeroZero/GOwallet" target="_blank">${t('开源代码', 'Source')}</a></footer>`; }
function frame(content: string) {
  document.documentElement.lang = english() ? 'en' : 'zh-CN';
  document.body.dataset.theme = dark() ? 'dark' : 'light';
  document.body.innerHTML = `<main class="shell">${header()}<section id="content">${content}</section>${footer()}</main>`;
  $('#language').onclick = () => { localStorage.setItem('lang', english() ? 'zh' : 'en'); render(); };
  $('#theme').onclick = () => { localStorage.setItem('theme', dark() ? 'light' : 'dark'); render(); };
}
function render() { frame(''); if (activeTab === 'assets') showHome(); else if (activeTab === 'activity') showActivity(); else if (activeTab === 'add') showAdd(); else showSettings(); }
function nav() { return `<nav class="bottom-nav"><button class="tab ${activeTab === 'assets' ? 'active' : ''}" data-tab="assets"><b>◈</b>${t('资产', 'Assets')}</button><button class="tab ${activeTab === 'activity' ? 'active' : ''}" data-tab="activity"><b>↔</b>${t('活动', 'Activity')}</button><button class="tab ${activeTab === 'add' ? 'active' : ''}" data-tab="add"><b>＋</b>${t('添加', 'Add')}</button><button class="tab ${activeTab === 'settings' ? 'active' : ''}" data-tab="settings"><b>⚙</b>${t('设置', 'Settings')}</button></nav>`; }
function bindNav() { document.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(button => button.onclick = () => { activeTab = button.dataset.tab || 'assets'; render(); }); }

async function showHome() {
  const content = $('#content');
  if (!mnemonic) {
    content.innerHTML = `<div class="welcome card"><div class="welcome-mark"><img src="assets/logo.svg" alt="GOwallet"></div><div class="eyebrow">GOWALLET · POW ASSETS</div><h1>${t('你的资产，你掌握', 'Your assets, your keys')}</h1><p>${t('轻量、非托管的多币种浏览器钱包', 'A compact, non-custodial wallet for PoW coins')}</p><div class="welcome-actions"><button class="button primary" id="create"><span>＋</span>${t('创建新钱包', 'Create wallet')}</button><button class="button secondary" id="restore">${t('恢复已有钱包', 'Restore wallet')}<span>›</span></button></div><div class="security-note"><span>✦</span>${t('助记词仅在本机生成和加密保存', 'Your seed is generated and encrypted locally')}</div></div>`;
    $('#create').onclick = () => setup(newMnemonic()); $('#restore').onclick = () => setup(''); return;
  }
  const coin = COINS[selected];
  content.innerHTML = `<div class="wallet-head"><div><div class="eyebrow">${t('钱包资产', 'PORTFOLIO')}</div><h1>${t('我的资产', 'My assets')}</h1></div><span class="safe"><b></b>${t('本地安全', 'Local secure')}</span></div><div class="total card"><div class="total-top"><span>${t('资产总览 · USD', 'Portfolio · USD')}</span><b>${t('实时估值未开启', 'Pricing off')}</b></div><strong>— <small>USD</small></strong><small>${t('仅显示节点同步余额', 'Node-synced balances only')}</small></div><div class="actions"><button class="button primary" id="receive-all">↓　${t('收款', 'Receive')}</button><button class="button secondary" id="send-all">↑　${t('发送', 'Send')}</button></div><div class="section-head"><strong>${t('我的币种', 'My coins')}</strong><span>${Object.keys(COINS).length} ${t('个资产　›', 'assets　›')}</span></div><div class="filters"><button class="filter active">${t('全部', 'All')}</button><button class="filter">${t('已添加', 'Added')}</button><button class="filter">${t('收藏', 'Favorites')}</button></div><div class="asset-list">${Object.values(COINS).map(x => `<button class="asset-row ${x.id === selected ? 'selected' : ''}" data-coin="${x.id}"><i class="asset-icon" style="background:${x.color}">${x.ticker[0]}</i><span class="identity"><strong>${x.name}</strong><small>${x.ticker} · ${x.id === selected ? t('当前选择', 'Selected') : t('可用网络', 'Network ready')}</small></span><span class="value"><strong>${x.id === selected ? '—' : '—'}</strong><small>${t('等待同步', 'Awaiting sync')}</small></span><span class="arrow">›</span></button>`).join('')}</div>${nav()}`;
  document.querySelectorAll<HTMLButtonElement>('[data-coin]').forEach(button => button.onclick = () => { selected = button.dataset.coin as CoinId; render(); });
  $('#receive-all').onclick = () => showReceive(); $('#send-all').onclick = () => alert(t('发送交易将在签名回归测试完成后开放。', 'Sending opens after signing regression tests pass.')); bindNav();
}

function showActivity() { $('#content').innerHTML = `<div class="page-head"><div class="eyebrow">ACTIVITY</div><h1>${t('活动记录', 'Activity')}</h1><p>${t('按币种查看节点返回的交易记录', 'Transactions returned by the selected Electrum node')}</p></div><div class="empty card"><div class="empty-icon">↔</div><strong>${t('暂无活动记录', 'No activity yet')}</strong><small>${t('选择币种并完成同步后，交易会显示在这里。', 'Transactions appear here after a coin is synchronized.')}</small></div>${nav()}`; bindNav(); }
function showAdd() { $('#content').innerHTML = `<div class="page-head"><div class="eyebrow">ADD ASSETS</div><h1>${t('添加币种', 'Add assets')}</h1><p>${t('选择已配置的 PoW 币种，或稍后添加自定义网络。', 'Choose a configured PoW coin, or add a custom network later.')}</p></div><div class="asset-list add-list">${Object.values(COINS).map(x => `<button class="asset-row" data-coin="${x.id}"><i class="asset-icon" style="background:${x.color}">${x.ticker[0]}</i><span class="identity"><strong>${x.name}</strong><small>${x.ticker} · Electrum</small></span><span class="add-mark">＋</span></button>`).join('')}</div><button class="button secondary full" id="custom">＋　${t('添加自定义网络', 'Add custom network')}</button>${nav()}`; document.querySelectorAll<HTMLButtonElement>('[data-coin]').forEach(button => button.onclick = () => { selected = button.dataset.coin as CoinId; activeTab = 'assets'; render(); }); $('#custom').onclick = () => alert(t('自定义 Electrum 网络将在下一版开放。', 'Custom Electrum networks are planned for the next build.')); bindNav(); }
function showSettings() { $('#content').innerHTML = `<div class="page-head"><div class="eyebrow">SETTINGS</div><h1>${t('设置', 'Settings')}</h1><p>${t('安全、语言和显示偏好', 'Security, language and appearance')}</p></div><div class="settings-list card"><button class="setting-row" id="theme-setting"><span><b>◐</b><strong>${t('显示主题', 'Theme')}</strong><small>${dark() ? t('深色模式', 'Dark mode') : t('浅色模式', 'Light mode')}</small></span><em>›</em></button><button class="setting-row" id="lang-setting"><span><b>文</b><strong>${t('语言 / Language', 'Language')}</strong><small>${english() ? 'English (US)' : '简体中文'}</small></span><em>›</em></button><button class="setting-row" id="lock-setting"><span><b>⌁</b><strong>${t('锁定钱包', 'Lock wallet')}</strong><small>${t('清除当前会话中的密钥', 'Clear the current session key')}</small></span><em>›</em></button></div>${nav()}`; $('#theme-setting').onclick = () => { localStorage.setItem('theme', dark() ? 'light' : 'dark'); render(); }; $('#lang-setting').onclick = () => { localStorage.setItem('lang', english() ? 'zh' : 'en'); render(); }; $('#lock-setting').onclick = () => { client?.close(); mnemonic = ''; activeTab = 'assets'; render(); }; bindNav(); }
function showReceive() { const coin = COINS[selected]; const address = derive(mnemonic, coin).address; $('#content').innerHTML = `<div class="page-head compact"><button class="back-button" id="back">‹　${t('返回资产', 'Back to assets')}</button><div class="eyebrow">${coin.ticker} · RECEIVE</div><h1>${t(`接收 ${coin.ticker}`, `Receive ${coin.ticker}`)}</h1><p>${t('分享二维码或复制地址，安全接收资产。', 'Share the QR code or copy the address.')}</p></div><div class="receive-card card"><div class="qr-placeholder"></div><div class="receive-address">${address}</div><button class="button primary full" id="copy-address">⧉　${t('复制收款地址', 'Copy address')}</button><div class="compact-notice">ⓘ　${t('请确认发送方使用正确的币种网络。', 'Confirm the sender uses the correct network.')}</div></div>`; $('#back').onclick = () => render(); $('#copy-address').onclick = async () => { try { await navigator.clipboard.writeText(address); $('#copy-address').textContent = t('已复制', 'Copied'); } catch { /* optional clipboard */ } }; }
function setup(initial: string) { frame(`<div class="form-page"><button class="back-button" id="back">‹　${t('返回', 'Back')}</button><div class="form card"><div class="form-icon">${initial ? '✦' : '↺'}</div><div class="eyebrow">${initial ? t('新钱包', 'NEW WALLET') : t('恢复钱包', 'RESTORE WALLET')}</div><h1>${initial ? t('设置钱包密码', 'Set wallet password') : t('恢复已有钱包', 'Restore wallet')}</h1><p class="form-lead">${initial ? t('密码保护本机钱包数据，无法找回遗失的助记词。', 'This password protects local data and cannot recover a lost seed.') : t('输入 12 个英文助记词，恢复本机钱包。', 'Enter your 12-word English seed to restore the wallet.')}</p>${initial ? `<div class="seed-box"><span>${t('请离线抄写并妥善保存', 'Write down and store offline')}</span><code>${initial}</code></div>` : '<textarea id="mnemonic" placeholder="输入 12 个英文助记词"></textarea>'}<label>${t('钱包密码', 'Wallet password')}<input id="password" type="password" minlength="12" placeholder="${t('至少 12 位字符', 'At least 12 characters')}"></label><button class="button primary full" id="save">${t('保存并进入', 'Save and continue')} <span>→</span></button><p class="error" id="error"></p></div></div>`); $('#back').onclick = () => render(); $('#save').onclick = async () => { const words = initial || $<HTMLTextAreaElement>('#mnemonic').value.trim(); const password = $<HTMLInputElement>('#password').value; if (!validMnemonic(words) || password.length < 12) { $('#error').textContent = t('请检查助记词和密码（密码至少 12 位）', 'Check your seed and password (12+ characters)'); return; } await saveVault(words, password); mnemonic = words; activeTab = 'assets'; render(); }; }
async function boot() { if (await hasVault()) { frame(`<div class="unlock-page"><div class="unlock-mark"><img src="assets/logo.svg"></div><div class="eyebrow">GOWALLET</div><h1>${t('欢迎回来', 'Welcome back')}</h1><p>${t('输入密码解锁本机钱包', 'Enter your password to unlock')}</p><div class="unlock-card card"><label>${t('钱包密码', 'Wallet password')}<input id="password" type="password" placeholder="••••••••••••"></label><button class="button primary full" id="unlock">${t('解锁钱包', 'Unlock wallet')} <span>→</span></button><p class="error" id="error"></p></div><button class="text-button" id="reset-view">${t('使用其他钱包', 'Use another wallet')}</button></div>`); $('#unlock').onclick = async () => { try { mnemonic = await loadVault($<HTMLInputElement>('#password').value) || ''; render(); } catch { $('#error').textContent = t('密码错误，请重试', 'Wrong password, try again'); } }; $('#reset-view').onclick = () => { mnemonic = ''; showHome(); }; } else render(); }
boot();
