import { COINS, type CoinId } from './coins.js';
import { derive,deriveAddress,newMnemonic,validMnemonic } from './wallet.js';
import { saveVault,loadVault,hasVault } from './vault.js';
import { ElectrumClient } from './electrum.js';
import { formatAmount } from './encoding.js';

let mnemonic=''; let selected:CoinId='scash'; let client:ElectrumClient|undefined;
const $=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
const lang=()=>localStorage.getItem('lang')==='en';
const t=(zh:string,en:string)=>lang()?en:zh;
function render(){document.documentElement.lang=lang()?'en':'zh-CN';document.body.innerHTML=`<main class="shell"><header><img src="../assets/logo.svg"><strong>GOwallet</strong><button id="language">${lang()?'中文':'EN'}</button></header><section id="content"></section><footer><small>非托管钱包 · 密钥仅保存在本机</small><a href="https://github.com/AlexZeroZero/GOwallet" target="_blank">开源代码</a></footer></main>`;showHome();}
async function showHome(){const c=$('#content');if(!mnemonic){c.innerHTML=`<div class="hero"><h1>${t('你的资产，你掌握','Your assets, your keys')}</h1><p>${t('GOwallet 浏览器扩展钱包','GOwallet browser wallet')}</p><button class="primary" id="create">${t('创建新钱包','Create wallet')}</button><button id="restore">${t('恢复已有钱包','Restore wallet')}</button></div>`;$<HTMLButtonElement>('#create').onclick=()=>setup(newMnemonic());$<HTMLButtonElement>('#restore').onclick=()=>setup('');return;}c.innerHTML=`<div class="row"><h2>${t('我的资产','My assets')}</h2><button id="lock">${t('锁定','Lock')}</button></div><nav>${Object.values(COINS).map(x=>`<button class="coin ${x.id===selected?'active':''}" data-coin="${x.id}"><i style="background:${x.color}">${x.ticker[0]}</i>${x.ticker}</button>`).join('')}</nav><article id="asset"><h3>${COINS[selected].name}（${COINS[selected].ticker}）</h3><div class="address" id="address"></div><div class="balance" id="balance">${t('连接节点中…','Connecting…')}</div><div class="actions"><button id="receive">${t('收款','Receive')}</button><button id="send">${t('发送','Send')}</button></div></article><p class="notice">${t('节点由币种项目或第三方独立运营；节点故障不改变链上资产归属。','Nodes are independently operated; an outage does not change on-chain ownership.')}</p>`;document.querySelectorAll<HTMLButtonElement>('[data-coin]').forEach(b=>b.onclick=()=>{selected=b.dataset.coin as CoinId;showHome()});$('#lock').onclick=()=>{client?.close();mnemonic='';showHome()};$('#receive').onclick=async()=>{try{await navigator.clipboard.writeText($('#address').textContent||'');$('#receive').textContent=t('已复制','Copied')}catch{}};$('#send').onclick=()=>alert(t('发送交易将在网关和签名回归测试完成后开放。请先使用收款和余额功能测试。','Send is gated until gateway and signing regression tests are complete. Use receive and balance first.'));refresh();}
async function refresh(){const coin=COINS[selected];const derived=derive(mnemonic,coin);$('#address').textContent=derived.address;try{client?.close();client=new ElectrumClient(coin.node);await client.verify(coin);const b=await client.balance(derived.scriptHash);$('#balance').textContent=formatAmount(BigInt(b.confirmed),coin.decimals)+' '+coin.ticker;}catch(e){$('#balance').textContent=t('节点暂不可用（请检查 WSS 网关）','Node unavailable (check WSS gateway)');}}
function setup(initial:string){const c=$('#content');c.innerHTML=`<div class="form"><h2>${initial?t('设置钱包密码','Set wallet password'):t('恢复钱包','Restore wallet')}</h2>${initial?`<p class="hint">${t('请离线抄写并妥善保存助记词：','Write down and securely store this mnemonic offline:')}</p><code class="mnemonic">${initial}</code>`:'<textarea id="mnemonic" placeholder="输入 12 个英文助记词"></textarea>'}<input id="password" type="password" minlength="12" placeholder="${t('密码至少 12 位','Password: at least 12 characters')}"><button class="primary" id="save">${t('保存并进入','Save and continue')}</button><p id="error"></p></div>`;$('#save').onclick=async()=>{const m=initial||$<HTMLTextAreaElement>('#mnemonic').value.trim(),p=$<HTMLInputElement>('#password').value;if(!validMnemonic(m)||p.length<12){$('#error').textContent=t('助记词或密码无效','Invalid mnemonic or password');return;}await saveVault(m,p);mnemonic=m;showHome();};}
async function boot(){if(await hasVault()){document.body.innerHTML=`<main class="shell"><header><img src="../assets/logo.svg"><strong>GOwallet</strong><button id="language">${lang()?'中文':'EN'}</button></header><div class="form"><h2>${t('解锁 GOwallet','Unlock GOwallet')}</h2><input id="password" type="password" placeholder="${t('钱包密码','Wallet password')}"><button class="primary" id="unlock">${t('解锁','Unlock')}</button><p id="error"></p></div></main>`;$<HTMLButtonElement>('#unlock').onclick=async()=>{try{mnemonic=await loadVault($<HTMLInputElement>('#password').value)||'';showHome()}catch{$('#error').textContent=t('密码错误','Wrong password')}};}else render();$('#language').onclick=()=>{localStorage.setItem('lang',lang()?'zh':'en');render()};}
boot();
