import 'package:bitfinite/gowallet/l10n/go_localizations.dart';
/*
 * This file is part of Stack Wallet.
 *
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/material.dart';

import '../../../themes/stack_colors.dart';

import '../../../utilities/text_styles.dart';

/// Empty transaction list — Miso at rest instead of a bare text row.
class NoTransActionsFound extends StatelessWidget {
  const NoTransActionsFound({super.key});

  @override
  Widget build(BuildContext context) {
    final colors = Theme.of(context).extension<StackColors>()!;

    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 24),
      child: Column(
        children: [
          Icon(
            Icons.receipt_long_outlined,
            size: 64,
            color: colors.textSubtitle1,
          ),
          const SizedBox(height: 12),
          Text(
            goTr(context, "暂无交易记录"),
            style: STextStyles.titleBold12(context),
          ),
          const SizedBox(height: 4),
          Text(
            goTr(context, "收款或发送后，交易记录会显示在这里。"),
            textAlign: TextAlign.center,
            style: STextStyles.itemSubtitle(context),
          ),
        ],
      ),
    );
  }
}
