import 'package:bitfinite/gowallet/l10n/go_localizations.dart';
/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/material.dart';
import '../../../../utilities/text_styles.dart';

class CreateRestoreWalletSubTitle extends StatelessWidget {
  const CreateRestoreWalletSubTitle({super.key, required this.isDesktop});

  final bool isDesktop;

  @override
  Widget build(BuildContext context) {
    return Text(
      goTr(context, "创建新的助记词，或恢复你已有的钱包。"),
      textAlign: TextAlign.center,
      style: isDesktop
          ? STextStyles.desktopSubtitleH2(context)
          : STextStyles.subtitle(context),
    );
  }
}
